# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie111', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.TextField()),
                ('user_s1', models.TextField()),
                ('user_s2', models.TextField()),
                ('user_s3', models.TextField()),
            ],
        ),
    ]
