# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie111', '0003_myrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.TextField()),
                ('theme_text', models.TextField()),
            ],
        ),
    ]
